### PR TITLE
Add go.mod and go.sum for Go module

### PR DESCRIPTION
**Pull request by flibustenet**
Just running `go mod init github.com/alexbrainman/odbc` and `go mod tidy`

It could be fine also to release with a semver version.

### CODE REVIEW

**Comment by alexbrainman** [comment]
Thank you.

I do not have time to review this. I will review when I have time.

Alex

**Comment by alexbrainman** [comment]
LGTM Thank you. Sorry for taking too long.

@flibustenet please rebase on master, and I will submit.

> currently working on a project and would find this change useful.

@T3RM1NU5 does this change fixes your problem?

Alex

**Comment by alexbrainman** [comment]
> @flibustenet please rebase on master, and I will submit.

Never mind, your commit does not need rebasing. I merged it. So closing this PR now.

Thank you.

Alex

**Comment by T3RM1NU5** [comment]
@alexbrainman and @flibustenet  thank you very much for that.  Also to answer your question yes it solves my problem. I am working on a build job for my project and I want to make use of Go Modules hence the need mod file.

**Comment by flibustenet** [comment]
@alexbrainman i thought i did the rebase. I didn't ?

**Comment by alexbrainman** [comment]
> i thought i did the rebase. I didn't ?

I did do rebase. I was mistaken. All is good.

Thank you.

Alex

**Pull request merged**
